baseURL = "https://prcore.gitlab.io"
title = "PrCore Documentation"
languageCode = "en-us"
theme = "hugo-geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
   tag = "tags"


[params]
  geekdocMenuBundle = false
  geekdocLogo = "images/logo-transparent.png"

defaultContentLanguage = "en"

[languages.en]
languageName = "English"
contentDir = "content/en"
weight = 10

# [languages.zh-cn]
# languageName = "中文"
# contentDir = "content/zh-cn"
# weight = 20
